#!/bin/bash
#
# Robert Nowotniak 2020 <rnowotniak@gmail.com>
#

token=$(cat .token)


list() {
	curl -s -H "Authorization: token $(cat .token)" https://api.github.com/user/repos | jq -r '.[].name'
	exit 0
}

help() {
	echo "Usage:"
	echo -e "\t$0  -h | help"
	echo -e "\t$0 [ list ]"
	echo -e "\t$0 create [ -d <description> ] [ -p ] <repo_name>"
	echo -e "\t$0 delete <repo_name>"
	echo
	exit 1
}

create() {
	private=false
	while getopts ":d:p" o; do
		case "$o" in
			d)
				description=$OPTARG
			;;
			p)
				private=true
			;;
			*)
				help
			;;
		esac
	done
	shift $((OPTIND-1))
	if [ "$#" -ne 1 ]; then
		help
	fi
	name="$1"
	curl -s -H "Authorization: token $(cat .token)" \
		-d "{\"name\":\"${1}\",\"description\":\"${description}\",\"private\":\"${private}\"}" \
		https://api.github.com/user/repos | jq -r '.html_url'
	exit 0
}

delete() {
	if [ "$#" -ne 1 ]; then
		help
	fi
	name="$1"

	curl -s -H "Authorization: token $(cat .token)" https://api.github.com/user

	#curl -s -H "Authorization: token $(cat .token)" \
	#	-X DELETE \
	#	https://api.github.com/user/repos | jq -r '.html_url'
	exit 0
}

while getopts "h" o; do
	case "$o" in
		h)
			help
		;;
		*)
			help
		;;
	esac
done
shift $((OPTIND-1))

case "$1" in
	"list" | "" )
		list
	;;
	"create" )
		shift
		create "$@"
	"delete" )
		shift
		delete "$@"
	;;
	"help"|*)
		help
	;;
esac

