#!/bin/bash
#
# Robert Nowotniak 2020-2022 <robert@nowotniak.com>
#

TOKEN_FILE=`dirname "$0"`/.github-cli-token
MAX_REPOS=9999999

if [ ! -r "$TOKEN_FILE" -o ! -s "$TOKEN_FILE" ]; then
	echo "Error: $TOKEN_FILE empty or missing."
	echo "Please generate your personal OAuth token in your GitHub account developer settings, and save it in $TOKEN_FILE"
	exit 1
fi

token=$(cat "$TOKEN_FILE")


list() {
	curl -s -H "Authorization: token ${token}" https://api.github.com/user/repos'?per_page='"$MAX_REPOS" | jq -r '.[].name'
	exit 0
}

help() {
	bname=`basename $0`

	echo "github-cli,  Robert Nowotniak 2020 <rnowotniak@gmail.com>"
	echo 
	echo "Usage:"
	echo -e "\t$bname  -h | help"
	echo -e "\t$bname [ list ]"
	echo -e "\t$bname create [ -d <description> ] [ -p ] <repo_name>"
	echo -e "\t            -p  means create a public repository (private is the default)"
	echo -e "\t$bname delete <repo_name> [ <repo_name> ... ]"
	echo -e "\t$bname info <repo_name> [ <repo_name> ... ]"
	echo ""
	echo "To be implemented:"
	echo -e "\t$bname publish <repo_name> [ <repo_name> ... ]"
	echo -e "\t$bname clone <repo_name> [ <repo_name> ... ]"
	echo
	exit 1
}

create() {
	private=true
	while getopts ":d:p" o; do
		case "$o" in
			d)
				description=$OPTARG
			;;
			p)
				private=false
			;;
			*)
				help
			;;
		esac
	done
	shift $((OPTIND-1))
	if [ "$#" -ne 1 ]; then
		help
	fi
	repo="$1"
	if [ -z "$description" ]; then
		description="$repo project"
	fi
	curl -s -H "Authorization: token ${token}" \
		-d "{\"name\":\"${repo}\",\"description\":\"${description}\",\"private\":${private}}" \
		https://api.github.com/user/repos | jq -r '.html_url'
	local ssh_url=$(info "$repo" | jq -r '.ssh_url')
	echo $ssh_url
	git clone "$ssh_url"
	exit 0
}

delete() {
	if [ "$#" -lt 1 ]; then
		help
	fi
	owner=$(curl -s -H "Authorization: token ${token}" https://api.github.com/user | jq -r '.login')
	[ "$owner" ] || exit 1

	for repo in "$@"; do 
		curl -s -H "Authorization: token ${token}" \
			-X DELETE \
			https://api.github.com/repos/"$owner"/"$repo" | jq -r '.message'
	done
	exit 0
}

info() {
	if [ "$#" -lt 1 ]; then
		help
	fi
	owner=$(curl -s -H "Authorization: token ${token}" https://api.github.com/user | jq -r '.login')
	[ "$owner" ] || exit 1

	for repo in "$@"; do 
		curl -s -H "Authorization: token ${token}" \
			https://api.github.com/repos/"$owner"/"$repo"
	done
}

while getopts "h" o; do
	case "$o" in
		h)
			help
		;;
		*)
			help
		;;
	esac
done
shift $((OPTIND-1))

case "$1" in
	"list" | "" )
		list
	;;
	"create" )
		shift
		create "$@"
	;;
	"delete" )
		shift
		delete "$@"
	;;
	"info" )
		shift
		info "$@"
	;;
	"help"|*)
		help
	;;
esac

